import { useCallback, useEffect, useState } from 'react';
import { api, amount } from '../../lib/market/api';
import { ProductEditor } from './Dashboard';
import Orders from './Orders';
export default function AccountHub({country='CD',resource:initial='listings',admin=false,viewer="buyer",config}) {
 const [resource,setResource]=useState(initial),[data,setData]=useState({}),[market,setMarket]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null),[editing,setEditing]=useState(null),[adding,setAdding]=useState(false);
 const load=useCallback(async()=>{try{setData(await api('/api/account-hub?resource='+resource+'&view='+viewer,{country}));if(['listings','returns'].includes(resource))setMarket(await api('/api/marketplace?view='+(resource==='listings'?'particular':'buyer'),{country}).catch(()=>null));}catch(e){setError(e.message)}},[country,resource,viewer]);
 useEffect(()=>{setData({});setError('');setSelected(null);void load()},[load]);
 async function act(body){setBusy(true);setError('');try{await api('/api/account-hub',{country,body});await load();setSelected(null);setAdding(false);setEditing(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const form=(submit,children)=><form className="yv-form" onSubmit={e=>{e.preventDefault();submit(Object.fromEntries(new FormData(e.currentTarget)))}}>{children}<button className="yv-primary" disabled={busy}>Enregistrer</button></form>;
 const input=(name,label,type='text')=><label>{label}<input name={name} type={type} required maxLength={type==='text'?2000:undefined}/></label>;
 const channel=<label>Canal<select name="channel"><option value="cash">Espèces</option><option value="bank">Banque</option><option value="mobile_money">Mobile Money</option></select></label>;
 const external=<label className="yv-check"><input name="confirmed" type="checkbox" required/>Je confirme que cette opération a déjà été effectuée à l’extérieur de YAVIYA.</label>;
 const titles={listings:'Mes annonces personnelles',finance:'Portefeuille et règlements',returns:'Retours et remboursements',addresses:'Mes adresses',support:'Dossiers service client',subscriptions:'Abonnements',admin:'Comptes et autorisations',content:'Promotions et publicités',reviews:'Évaluations reçues',shops:'Mes boutiques'};
 return <section className="yv-dashboard"><nav className="yv-tabs" aria-label="Outils du compte">{Object.entries(titles).filter(([r])=>admin || !['admin','content'].includes(r)).map(([r,label])=><button key={r} aria-pressed={resource===r} onClick={()=>setResource(r)}>{label}</button>)}</nav><h3>{titles[resource]}</h3><button onClick={load}>Actualiser</button>{error&&<p className="yv-error" role="alert">{error}</p>}
 {resource==='listings'&&<><p>Revendez occasionnellement vos articles neufs ou d’occasion, sans boutique professionnelle. Commission YAVIYA : <strong>12 %</strong> du prix des articles, calculée par le serveur. Les annonces sont examinées avant publication.</p>{!data.sellerId?<button className="yv-primary" disabled={busy} onClick={()=>act({action:'enable_particular',acceptCommission:true})}>Accepter les 12 % et activer mes annonces</button>:<><button onClick={()=>{setAdding(true);setEditing(null)}}>Ajouter une annonce personnelle</button>{(adding||editing)&&market&&<ProductEditor key={editing?.id || 'new'} product={editing} state={{...market,personal:true,sellerIds:[data.sellerId],catalogue:data.listings || [],stores:[{id:data.sellerId,name:'Mes annonces personnelles'}]}} config={config} country={country} onSaved={async()=>{setAdding(false);setEditing(null);await load()}}/>}{(data.listings || []).map(p=><article className="yv-info-card" key={p.id}><h4>{p.title}</h4><p>{amount(p.price,country)} · {p.approved?'Annonce approuvée':'En attente de validation'}</p><button onClick={()=>{setEditing(p);setAdding(false)}}>Modifier l’annonce</button></article>)}{market&&<Orders state={market} country={country} role="seller" onRefresh={load}/>}</>}</>}
 {resource==='finance'&&<><p>{data.notice}</p><p className="yv-muted">Le portefeuille monétaire n’est pas activé. Les YaviCoins / coupons restent en démonstration.</p>{(data.summary || []).map(s=><p key={s.currency}>Synthèse {s.currency} : ventes {s.gross} · commissions {s.commission} · net {s.net}</p>)}{(data.entries || []).filter(e=>e.seller_id===0).map(e=><p key={e.id}>{e.order_id} · {e.kind==='payout_manual'?'Règlement externe déclaré':'Rémunération livraison comptabilisée'} : {e.amount} {e.currency}</p>)}<div className="yv-table"><table><thead><tr><th>Commande</th><th>Ventes</th><th>Commission</th><th>Net</th><th>Statut</th></tr></thead><tbody>{(data.settlements || []).map(s=><tr key={s.id}><td>{s.order_id}</td><td>{amount(s.gross,country)}</td><td>{amount(s.commission,country)}</td><td>{amount(s.net,country)}</td><td>{s.status==='paid_manual'?'Règlement externe déclaré · '+s.reference:s.status==='refunded'?'Remboursement déclaré':s.status==='seller_collected'?'Vendeur déjà encaissé · commission due à YAVIYA':s.payable?'À régler':'En attente / bloqué'}{admin&&s.commissionCollectible&&<button onClick={()=>setSelected({...s,operation:'commission_receipt'})}>Enregistrer la commission reçue</button>}{admin&&s.payable&&<button onClick={()=>setSelected(s)}>Déclarer un règlement effectué</button>}</td></tr>)}</tbody></table></div>{admin&&(data.cashOrders || []).map(o=><article key={o.id} className="yv-info-card"><p>{o.id} · Espèces à rapprocher : {amount(o.total,country)}</p><button onClick={()=>setSelected({...o,operation:'cash_remittance'})}>Enregistrer les fonds effectivement reçus</button></article>)}{selected&&form(d=>act({action:selected.operation || 'seller_payout',id:selected.id,orderId:selected.id,amount:Number(d.amount),reference:d.reference,channel:d.channel,externalOperationConfirmed:d.confirmed==='on'}),<>{selected.operation&&input('amount','Montant effectivement reçu *','number')}{input('reference','Référence de l’opération *')}{channel}{external}</>)}</>}
 {resource==='returns'&&<><p>Ouvrez votre demande dans les 72 heures suivant la réception. Les dossiers en cours bloquent le reversement vendeur.</p>{!admin&&form(d=>act({action:'return_request',...d}),<><label>Commande reçue<select name="orderId" required><option value="">Choisir…</option>{market?.orders.filter(o=>o.buyerConfirmed&&!o.cancelled).map(o=><option key={o.id}>{o.id}</option>)}</select></label>{input('reason','Motif *')}</>)}{(data.returns || []).map(r=><article className="yv-info-card" key={r.id}><h4>{r.order_id} · {r.status}</h4><p>{r.reason}</p><p>{r.note}</p>{admin&&!['refunded_manual','rejected'].includes(r.status)&&<button onClick={()=>setSelected(r)}>Traiter le retour</button>}</article>)}{admin&&selected&&form(d=>act({action:'return_decision',id:selected.id,revision:selected.revision,status:d.status,note:d.note,reference:d.reference,channel:d.channel,externalOperationConfirmed:d.confirmed==='on'}),<><label>Décision<select name="status">{(selected.status==='requested'?['approved','rejected']:selected.status==='approved'?['received']:['refunded_manual']).map(s=><option key={s} value={s}>{{approved:'Autoriser le retour',rejected:'Refuser',received:'Confirmer le retour reçu',refunded_manual:'Enregistrer le remboursement déjà effectué'}[s]}</option>)}</select></label>{input('note','Justification *')}{selected.status==='received'&&<>{input('reference','Référence du remboursement *')}{channel}{external}</>}</>)}</>}
 {resource==='shops'&&<>{(data.shops || []).map(s=><article className="yv-info-card" key={s.id}><h4>{s.name}</h4><p>{s.address}</p><button onClick={()=>setSelected(s)}>Modifier la boutique</button></article>)}{form(d=>act({action:'shop_save',id:selected?.id,name:d.name,address:d.address,addressConfirmed:d.confirmed==='on'}),<>{input('name','Nom de la boutique *')}{input('address','Adresse de la boutique *')}<label className="yv-check"><input name="confirmed" type="checkbox" required/>Je confirme l’adresse de cette boutique.</label></>)}</>}
 {resource==='addresses'&&<>{(data.addresses || []).map(a=><article className="yv-info-card" key={a.id}><h4>{a.label}</h4><p>{a.address} · {a.commune}, {a.city}</p><button disabled={busy} onClick={()=>act({action:'address_delete',id:a.id})}>Supprimer</button></article>)}{form(d=>act({action:'address_save',...d}),<>{input('label','Nom de l’adresse *')}<label>Ville<select name="city">{config.deliverableCities.map(c=><option key={c}>{c}</option>)}</select></label>{input('commune','Commune *')}{input('address','Adresse *')}{input('phone','Téléphone *')}</>)}</>}
 {resource==='support'&&<>{!admin&&form(d=>act({action:'support_create',...d}),<><label>Sujet<select name="topic">{['Livraison','Remboursement','Problème de compte','Coupon','Commande','Paiement'].map(t=><option key={t}>{t}</option>)}</select></label>{input('message','Votre demande *')}</>)}{(data.tickets || []).map(t=><article className="yv-info-card" key={t.id}><h4>{t.topic} · {t.status==='resolved'?'Résolu':'Ouvert'}</h4>{t.messages.map(m=><p key={m.id}><strong>{m.sender_role==='admin'?'YAVIYA':'Client'} :</strong> {m.message}</p>)}<button onClick={()=>setSelected(t)}>Répondre</button></article>)}{selected&&form(d=>act({action:'support_reply',id:selected.id,revision:selected.revision,message:d.message,status:d.status || 'open'}),<>{input('message','Réponse *')}{admin&&<label>Statut<select name="status"><option value="open">En cours</option><option value="resolved">Résolu</option></select></label>}</>)}</>}
 {resource==='subscriptions'&&<><p>Enregistrez votre intérêt. Aucun abonnement n’est activé ni facturé tant que le prestataire financier n’est pas configuré.</p>{(data.requests || []).map(r=><p key={r.id}>{r.kind} · {r.plan} · Demande non payée</p>)}{!admin&&form(d=>act({action:'subscription_request',...d}),<><label>Type<select name="kind"><option value="delivery">Livraison</option><option value="seller">Vendeur</option></select></label><label>Forfait<select name="plan">{['monthly','annual','free','plus','premium','business','enterprise'].map(p=><option key={p}>{p}</option>)}</select></label></>)}</>}
 {resource==='reviews'&&<>{(data.reviews || []).map(r=><article className="yv-info-card" key={r.orderId}><h4>{r.orderId}</h4><p>{r.comment || 'Évaluation reçue'}</p>{Object.entries(r.sellerScores || {}).map(([id,score])=><p key={id}>{r.sellerNames?.[id] || 'Vendeur'} : {score} / 5</p>)}{r.courierScore&&<p>Livreur : {r.courierScore} / 5</p>}</article>)}</>}
 {resource==='admin'&&admin&&<><h4>Commission professionnelle</h4><p>Taux actuel : {data.professionalCommissionBps===null?'À définir':Number(data.professionalCommissionBps)/100+' %'}. Changements applicables aux nouvelles commandes uniquement.</p>{form(d=>act({action:'professional_commission',basisPoints:Math.round(Number(d.percent)*100)}),input('percent','Commission (%)','number'))}<h4>Comptes et autorisations</h4>{(data.users || []).map(u=><article className="yv-info-card" key={u.user_id}><h4>{u.name}</h4><p>{u.account_type} · {u.suspended?'Suspendu':'Actif'}</p><button onClick={()=>setSelected(u)}>Gérer ce compte</button></article>)}{selected&&form(d=>act({action:d.action,userId:selected.user_id,suspended:!selected.suspended,role:d.role,note:d.note}),<><label>Action<select name="action"><option value="suspend_account">{selected.suspended?'Réactiver':'Suspendre'}</option><option value="revoke_role">Révoquer un rôle</option></select></label><label>Rôle<select name="role"><option value="seller">Vendeur</option><option value="courier">Livreur</option></select></label>{input('note','Justification *')}</>)}<h4>Historique des actions</h4>{(data.audit || []).map(a=><p key={a.id}>{new Date(a.created_at).toLocaleString('fr')} · {a.action} · {a.target}</p>)}</>}
 {resource==='content'&&admin&&<>{(data.content || []).map(c=><article className="yv-info-card" key={c.id}><p>{JSON.parse(c.data).title} · {JSON.parse(c.data).enabled?'Actif':'Brouillon'}</p><button onClick={()=>act({action:'content_save',id:c.id,kind:c.kind,data:{...JSON.parse(c.data),enabled:!JSON.parse(c.data).enabled}})}>Activer / désactiver</button></article>)}<p>Préparez une publicité ou une promotion. Vous pouvez enregistrer un brouillon ou activer le contenu. Les promotions mettent à jour le prix du produit côté serveur.</p>{form(d=>act({action:'content_save',kind:d.kind,data:{title:d.title,image:d.image,productId:Number(d.productId),price:Number(d.price),regularPrice:Number(d.regularPrice),enabled:d.enabled === "on"}}),<><label>Contenu<select name="kind"><option value="advertisement">Publicité</option><option value="promotion">Promotion</option></select></label>{input('title','Titre *')}<label className="yv-check"><input name="enabled" type="checkbox"/>Activer ce contenu</label><label>Image HTTPS<input name="image" type="url"/></label><label>Produit<input name="productId" type="number"/></label><label>Prix promotion<input name="price" type="number"/></label><label>Ancien prix<input name="regularPrice" type="number"/></label></>)}</>}
 </section>;
}
