export default function WhyYaviya({ onSeller, onNavigate }) {
  return (
    <section className="yv-why-yaviya">
      <header className="yv-why-intro">
        <p className="yv-eyebrow">POURQUOI YAVIYA ?</p>
        <h3>Plus de choix. Plus de proximité. Une nouvelle façon d’acheter.</h3>
        <p>Un achat réussi commence par une bonne découverte. Avec YAVIYA, retrouvez dans un même espace les produits qui accompagnent votre quotidien, les boutiques qui les proposent et les outils pour préparer votre commande. Notre ambition : vous rapprocher des bonnes offres, donner davantage de visibilité aux commerçants et construire un marché plus accessible, ancré dans les besoins de nos communautés.</p>
      </header>
      <div className="yv-why-grid">
        <article><h4>Un univers de produits pour chaque envie</h4><p>Équiper votre maison, renouveler votre garde-robe, préparer la rentrée, trouver un cadeau ou développer votre activité : vos besoins évoluent, votre marché doit vous suivre. Explorez les catégories alimentation, mode, beauté, électronique, automobile, musique, sport et bien d’autres. Les filtres, la recherche et les fiches produits vous aident à passer de l’idée au produit qui vous correspond.</p><p>Plutôt que de multiplier les recherches, prenez le temps de comparer les offres dans un environnement organisé. Vous gardez la liberté de découvrir de nouvelles boutiques et de choisir selon vos priorités.</p></article>
        <article><h4>Les informations utiles avant de choisir</h4><p>Un prix clair, une description et plusieurs photos vous permettent de mieux examiner un produit. Lorsqu’une offre promotionnelle présente un ancien prix, il apparaît barré à côté du nouveau prix pour rendre la comparaison immédiate. Vos favoris vous aident à conserver vos découvertes et à y revenir au moment qui vous convient.</p><p>Besoin d’un détail supplémentaire ? Le centre d’aide vous accompagne pour comprendre les étapes et préparer votre achat avec davantage de repères.</p></article>
        <article><h4>Des boutiques à découvrir et à retrouver</h4><p>Derrière chaque boutique, il y a une activité, un savoir-faire et des produits à faire connaître. YAVIYA donne aux commerçants un espace pour présenter leur offre et permet aux acheteurs de suivre les boutiques qui les intéressent. Vos magasins suivis restent accessibles depuis votre profil : une façon simple de retrouver vos préférés sans repartir de zéro.</p><p>La certification YAVIYA identifie les vendeurs dont le dossier a été validé. Elle constitue un repère sur la vérification du vendeur ; elle ne remplace pas l’examen de la fiche produit ni vos questions avant l’achat.</p></article>
        <article><h4>Une commande que vous pouvez suivre</h4><p>Votre relation avec YAVIYA continue après le choix d’un produit. Retrouvez votre historique, consultez le suivi et accédez aux mises à jour depuis les notifications. Ces repères vous permettent de revenir à votre commande et de savoir quelle est la prochaine étape.</p><p>Après la livraison, votre évaluation du vendeur et du livreur aide à partager votre expérience. Vos retours contribuent à faire évoluer la qualité du service et à donner des repères aux prochains acheteurs.</p></article>
        <article><h4>La livraison se prépare avec votre adresse</h4><p>Votre ville, votre commune et votre adresse sont essentielles pour organiser la réception. Renseignez votre lieu de livraison dans la commande pour consulter les frais correspondants avant de confirmer. Les zones ouvertes au service sont identifiées dans le parcours afin de vous guider dès la préparation de l’achat.</p><p>Vous disposez ainsi des éléments pour comparer votre panier et les frais de livraison, puis décider en fonction de votre budget et de votre localisation.</p></article>
        <article><h4>Un espace personnel qui vous simplifie la vie</h4><p>Votre profil rassemble vos commandes, vos coordonnées, les boutiques suivies, les coupons disponibles et les paramètres du compte. Vous pouvez retrouver vos informations utiles, consulter les conditions de vos avantages et partager votre lien d’invitation avec vos proches.</p><p>Chaque fonctionnalité poursuit le même objectif : vous faire gagner en clarté et vous permettre de revenir facilement à ce qui compte pour vous.</p></article>
        <article><h4>Une nouvelle vitrine pour votre commerce</h4><p>Vous vendez déjà en boutique ou souhaitez faire découvrir votre offre ? YAVIYA vous aide à présenter vos produits, à ajouter plusieurs photos et à structurer votre présence auprès des acheteurs. Votre espace vendeur réunit les outils de gestion du catalogue, des commandes et des statistiques de consultation.</p><p>Le nombre de personnes qui suivent votre boutique vous donne aussi un repère concret sur l’intérêt porté à votre activité. L’inscription par étapes vous accompagne dans la préparation de votre dossier et le choix de votre abonnement, selon les conditions affichées.</p></article>
        <article><h4>Une aide accessible, au bon moment</h4><p>Une question sur votre achat, le suivi ou la réception ? Le chatbot vous oriente vers les réponses du centre d’aide et vous permet d’accéder au service client si vous avez besoin d’un accompagnement. Les questions populaires rassemblent les situations courantes pour vous aider à avancer.</p><p>En cas de problème à la réception, la rubrique Retours et remboursements explique comment signaler votre demande sous 36 heures et faire examiner votre dossier. Vous savez où trouver l’aide et quelles informations préparer.</p></article>
      </div>
      <aside className="yv-why-outro"><h4>Votre prochaine découverte commence ici.</h4><p>Que vous cherchiez un produit, une boutique à suivre ou une nouvelle vitrine pour votre activité, faites de YAVIYA votre point de départ. Découvrez, comparez et préparez vos prochaines commandes dans un espace pensé pour vous rapprocher du marché.</p><div className="yv-actions"><button className="yv-primary" onClick={()=>onNavigate('catalogue')}>Découvrir les produits</button><button onClick={onSeller}>Ouvrir ma boutique</button><button onClick={()=>onNavigate('support')}>Parler au chatbot</button></div></aside>
    </section>
  );
}
